!#/bin/bash
wget "http://videos.securitytube.net/JackFlack-Banks.flv"
wget "http://videos.securitytube.net/Java-and-JNLP-Application-Hacking.flv"
wget "http://videos.securitytube.net/JavaScriptDecoding-Hartstien.flv"
wget "http://videos.securitytube.net/Kernel Patching.mp4"
wget "http://videos.securitytube.net/Learning-Wilson.flv"
wget "http://videos.securitytube.net/MVI_0968.AVI"
wget "http://videos.securitytube.net/Macchanger.flv"
wget "http://videos.securitytube.net/Malicious-Email-Social-Engineer-Attack-using-Social-Engineers-Toolkit-\(SET\).mp4"
wget "http://videos.securitytube.net/Malware-Unpacking-in-OllyDbg.swf"
wget "http://videos.securitytube.net/Memory-Allocation-with-Malloc,-Calloc-and-Realloc-Part-I-\(C-Programming-101\).flv"
wget "http://videos.securitytube.net/Memory-Allocation-with-Malloc,-Calloc-and-Realloc-Part-II-\(C-Programming-101\).flv"
wget "http://videos.securitytube.net/Metasploit-1-auxiliary smb login check.ogv"
wget "http://videos.securitytube.net/Metasploit-1-auxiliary-portscan.ogv"
wget "http://videos.securitytube.net/Metasploit-1-auxiliary-smb version.ogv"
wget "http://videos.securitytube.net/Metasploit-10.mp4"
wget "http://videos.securitytube.net/Metasploit-11.mp4"
wget "http://videos.securitytube.net/Metasploit-12.mp4"
wget "http://videos.securitytube.net/Metasploit-13.mp4"
wget "http://videos.securitytube.net/Metasploit-14.mp4"
wget "http://videos.securitytube.net/Metasploit-15.mp4"
wget "http://videos.securitytube.net/Metasploit-16.mp4"
wget "http://videos.securitytube.net/Metasploit-17.mp4"
wget "http://videos.securitytube.net/Metasploit-2-hacking xp sp3\(bind\).ogv"
wget "http://videos.securitytube.net/Metasploit-2-hacking xp sp3\(reverse\).ogv"
wget "http://videos.securitytube.net/Metasploit-2-hacking xp sp3\(vncinject\).ogv"
wget "http://videos.securitytube.net/Metasploit-3-backdoor-Encryption-Python.ogv"
wget "http://videos.securitytube.net/Metasploit-3-backdoor-Python.ogv"
wget "http://videos.securitytube.net/Metasploit-3-make a backdoor  linux-x86.mp4"
wget "http://videos.securitytube.net/Metasploit-3-make and encode a backdoor \(with metasploit and sniff email u-p\).ogv"
wget "http://videos.securitytube.net/Metasploit-3.mp4"
wget "http://videos.securitytube.net/Metasploit-4-meterpreter commands.ogv"
wget "http://videos.securitytube.net/Metasploit-4-meterpreter metscv.ogv"
wget "http://videos.securitytube.net/Metasploit-4-meterpreter packets sniffing .ogv"
wget "http://videos.securitytube.net/Metasploit-4-meterpreter-Screen And Keyscan.ogv"
wget "http://videos.securitytube.net/Metasploit-4-meterpreter-soundrecorder.ogv"
wget "http://videos.securitytube.net/Metasploit-4.mp4"
wget "http://videos.securitytube.net/Metasploit-5-Remote-BufferO-verflow.ogv"
wget "http://videos.securitytube.net/Metasploit-5-Remote-bof-egg-hunter.ogv"
wget "http://videos.securitytube.net/Metasploit-5-autopwn.ogv"
wget "http://videos.securitytube.net/Metasploit-5-browser autopwn.mp4"
wget "http://videos.securitytube.net/Metasploit-5-faka update.mp4"
wget "http://videos.securitytube.net/Metasploit-5-file autopwn.mp4"
wget "http://videos.securitytube.net/Metasploit-5-java signed applet.mp4"
wget "http://videos.securitytube.net/Metasploit-5.mp4"
wget "http://videos.securitytube.net/Metasploit-6.mp4"
wget "http://videos.securitytube.net/Metasploit-7.mp4"
wget "http://videos.securitytube.net/Metasploit-8.mp4"
wget "http://videos.securitytube.net/Metasploit-9.mp4"
wget "http://videos.securitytube.net/Metasploit-Megaprimer-1.mp4"
wget "http://videos.securitytube.net/Metasploit-Megaprimer-2.mp4"
wget "http://videos.securitytube.net/Methods-for-Analyzing-Malicious-Office-Documents-\(Recon-2008\).flv"
wget "http://videos.securitytube.net/Monitoring API Calls on Windows with Maltrap.mp4"
wget "http://videos.securitytube.net/More-Tricks-for-Defeating-SSL-\(Defcon-17\).mp4"
wget "http://videos.securitytube.net/Ncat-Demo-by-IronGeek.swf"
wget "http://videos.securitytube.net/NetWare-Kernel-Stack-Overflow-Exploitation-\(Recon-2008\).flv"
wget "http://videos.securitytube.net/Netbios-Basics-using-SMBClient-Part-1-.flv"
wget "http://videos.securitytube.net/Netbios-Basics-using-SMBClient-Part-2.flv"
wget "http://videos.securitytube.net/Netcat-Basics-\(Bind-Remote-Shell\).flv"
wget "http://videos.securitytube.net/Netcat-Basics-\(Client-Mode\).flv"
wget "http://videos.securitytube.net/Netcat-Basics-\(Server-Mode\).flv"
wget "http://videos.securitytube.net/Netifera-\(Java-Virtual-Machine-as-Shellcode\).mov"
wget "http://videos.securitytube.net/Netstumbler-\(Part-1\).flv"
wget "http://videos.securitytube.net/Netstumbler-\(Part-2\).flv"
wget "http://videos.securitytube.net/Network-Grep-\(Ngrep\)-Basics.flv"
wget "http://videos.securitytube.net/Network-Vulnerability-Assessment-Basics.swf"
wget "http://videos.securitytube.net/Nmap-\(-OS-and-Service-Fingerprinting\).flv"
wget "http://videos.securitytube.net/Nmap-Primer.flv"
wget "http://videos.securitytube.net/Nmap-Usage-Basics.flv"
wget "http://videos.securitytube.net/Non-Linear-Authentication.mp4"
wget "http://videos.securitytube.net/Nsploit-\(Popping-Boxes-with-Nmap\)-SecTor-2009.flv"
wget "http://videos.securitytube.net/Nuit-du-Hack-2010.flv"
wget "http://videos.securitytube.net/OfflineWeb-Sutton.flv"
wget "http://videos.securitytube.net/Open-Source-Information-Gathering-\(Brucon-2009\).flv"
wget "http://videos.securitytube.net/PCI-Panel.flv"
wget "http://videos.securitytube.net/PSTN-based-Cartography.flv"
wget "http://videos.securitytube.net/Packet-Injection-Basics-Presentation.flv"
wget "http://videos.securitytube.net/Packet-Sniffing-With-Ettercap.flv"
wget "http://videos.securitytube.net/Packet-Sniffing-using-Tcpdump.flv"
wget "http://videos.securitytube.net/Packet-Sniffing-using-Wireshark.flv"
wget "http://videos.securitytube.net/Password-Sniffing-with-Wireshark-\(Laura-Chappell\).mp4"
wget "http://videos.securitytube.net/Pcap2air.flv"
wget "http://videos.securitytube.net/Phishing Attack Demo using the Social Engineering Toolkit.mp4"
wget "http://videos.securitytube.net/Phishing-Attack-Demo-using-the-Social-Engineering-Toolkit.mp4"
wget "http://videos.securitytube.net/Physical-Security-\(Corkys-Security-Series\).flv"
wget "http://videos.securitytube.net/Pirni-MITM-Attack-with-iPhone.flv"
wget "http://videos.securitytube.net/Pirni-MITM-Attack-with-iPhone.mp4"
wget "http://videos.securitytube.net/Polymorphic-Virus-Analysis-\(Recon-2008\).flv"
wget "http://videos.securitytube.net/Prism-Strip.flv"
wget "http://videos.securitytube.net/Privacy Breach and Information Leakage through Installed Software.mp4"
wget "http://videos.securitytube.net/Programming-an-ARP-DoS-Tool-\(2\).flv"
wget "http://videos.securitytube.net/Programming-an-ARP-DoS-Tool.flv"
wget "http://videos.securitytube.net/Programming-the-Framework.flv"
wget "http://videos.securitytube.net/Public-Key-Cryptography.flv"
wget "http://videos.securitytube.net/Python-Web.flv"
wget "http://videos.securitytube.net/RC4-Basics-Presentation-\(2\).flv"
wget "http://videos.securitytube.net/RC4-Basics-Presentation.flv"
wget "http://videos.securitytube.net/RC4-File-Encrypt-Decrypt-Program.flv"
wget "http://videos.securitytube.net/RC4-Simulation-using-C.flv"
wget "http://videos.securitytube.net/RSol-Hillman.flv"
wget "http://videos.securitytube.net/Rage-Against-The-Kiosk-\(Brucon-2009\).flv"
wget "http://videos.securitytube.net/Raw-Sockets-Basics-Presentation-\(2\).flv"
wget "http://videos.securitytube.net/Raw-Sockets-Basics-Presentation.flv"
wget "http://videos.securitytube.net/Reading-and-Writing-Barcodes.mp4"
wget "http://videos.securitytube.net/Red-and-Tiger-Team-\(Brucon-2009\).flv"
wget "http://videos.securitytube.net/Remote-Keylogger-Firefox-Addon.flv"
wget "http://videos.securitytube.net/Reverse Engineering 101 \( Using IDA to break password protections \).mp4"
wget "http://videos.securitytube.net/Reverse Engineering 101 \( Using IDA to break password protections \)_controller.swf"
wget "http://videos.securitytube.net/Reverse Engineering 101 \( Using a Hex Editor to Find Passwords \).mp4"
wget "http://videos.securitytube.net/Reverse Engineering and Software Cracking Demo.mp4"
wget "http://videos.securitytube.net/Reverse-DNS-Lookup-with-DIG.mp4"
wget "http://videos.securitytube.net/Reverse-DNS-Lookup-with-DIG_controller.swf"
wget "http://videos.securitytube.net/Reverse-Engineering-101-\(-Using-a-Hex-Editor-to-Find-Passwords-\).mp4"
wget "http://videos.securitytube.net/Reverse-Engineering-101-\(-Using-a-Hex-Editor-to-Find-Passwords-\)_controller.swf"
wget "http://videos.securitytube.net/Reverse-Engineering-Dynamic-Languages-\(Recon-2008\).flv"
wget "http://videos.securitytube.net/Reverse-Engineering-Network-Utilities-Using-Wireshark.mp4"
wget "http://videos.securitytube.net/Reverse-Engineering-a-Software-Install-Process.mp4"
wget "http://videos.securitytube.net/Reverse-Engineering-over-Acrobat-Reader-using-Immunity-Debugger-\(RECON\).flv"
wget "http://videos.securitytube.net/Reverse-Engineering-the-Storm-Worm.flv"
wget "http://videos.securitytube.net/Ring-1-Markowsky.flv"
wget "http://videos.securitytube.net/RogueAP-Bratus.flv"
wget "http://videos.securitytube.net/SAP-Penetration-Testing-\(Blackhat-2009\).flv"
wget "http://videos.securitytube.net/SQL-Injection-\(Infinity-Exists\).flv"
wget "http://videos.securitytube.net/SQL-Injection-Attack-\(Corkys-Security-Series\).flv"
wget "http://videos.securitytube.net/SQL-Injection-Basics.flv"
wget "http://videos.securitytube.net/SQL-Injection-Worms-for-Fun-and-Profit.flv"
wget "http://videos.securitytube.net/SSL-MITM-Attack-Over-Wireless-Demo.flv"
wget "http://videos.securitytube.net/SSL-MITM-Attack-Over-Wireless.flv"
wget "http://videos.securitytube.net/Sagan-NFISSA.flv"
wget "http://videos.securitytube.net/Satellite-Hacking-for-Fun-and-Profit-\(Blackhat-2009\).flv"
wget "http://videos.securitytube.net/Satellite-Hacking-for-Fun-and-Profit-\(Blackhat-2009\).jpg"
wget "http://videos.securitytube.net/Scenario-Based-Hacking-1.mp4"
wget "http://videos.securitytube.net/Scenario-Based-Hacking-2a.mp4"
wget "http://videos.securitytube.net/Script-Fragmentation-\(A-new-Web-Attack-Vector\)-Brucon-2009.flv"
wget "http://videos.securitytube.net/Sending-Messages-using-IPC-Framework.flv"
wget "http://videos.securitytube.net/Sentinel-Keynote.flv"
wget "http://videos.securitytube.net/Setting-up-GeoIP-to-Track-IP-Address-Locations-in-Wireshark.mp4"
wget "http://videos.securitytube.net/Sfuzz-Fuzzer-Demo.mp4"
wget "http://videos.securitytube.net/Sidejacking-using-Ferret-and-Hamster-2.flv"
wget "http://videos.securitytube.net/Simple-Linux-Malware-Construction-by-Netinfinity.flv"
wget "http://videos.securitytube.net/Simple-Malware-Analyzing.flv"
wget "http://videos.securitytube.net/Simple-Replay.flv"
wget "http://videos.securitytube.net/Slow-Dll-Hijack-Vulnerability-Exploitation-using-DllHijackAuditor.flv"
wget "http://videos.securitytube.net/Smart-Parking-Meter-Implementations,-Globalism,-and-You-\(Defcon-17\).mp4"
wget "http://videos.securitytube.net/Smartphone-Hawthorn.flv"
wget "http://videos.securitytube.net/Snort-Overview-\(Corkys-Security-Series\).flv"
wget "http://videos.securitytube.net/Social-Engineering-for-the-Socially-Inept-\(Recon-2008\).flv"
wget "http://videos.securitytube.net/Socket-Programming-Basics-Presentation-\(2\).flv"
wget "http://videos.securitytube.net/Socket-Programming-Basics-Presentation-\(3\).flv"
wget "http://videos.securitytube.net/Socket-Programming-Basics-Presentation.flv"
wget "http://videos.securitytube.net/Software Cracking Primer using Ollydbg and a Crackme.mp4"
wget "http://videos.securitytube.net/SplendiferousStory-Scott.flv"
wget "http://videos.securitytube.net/Sqlninja-\(GUI-Access-Demo\).swf"
wget "http://videos.securitytube.net/Sqlninja-\(Sql-Injection-and-Takeover-Tool\).swf"
wget "http://videos.securitytube.net/Stoned-Bootkit-Demo.mp4"
wget "http://videos.securitytube.net/Storing Mined Data from the Web for Fun and Profit.mp4"
wget "http://videos.securitytube.net/Storing Mined Data from the Web for Fun and Profit_controller.swf"
wget "http://videos.securitytube.net/Structures-\(C-Programming-101\).flv"
wget "http://videos.securitytube.net/Symmetric-Key-Cryptography.flv"
wget "http://videos.securitytube.net/Syscall-hijacking-on-a-Compromised-Machine-for-Rootkit-Purposes.flv"
wget "http://videos.securitytube.net/System-Level-Privilege-Escalation-on-XP.flv"
wget "http://videos.securitytube.net/System-Management-Mode-Rootkit.flv"
wget "http://videos.securitytube.net/TCP-Echo-Client-using-Sockets.flv"
wget "http://videos.securitytube.net/TCP-Echo-Server-using-Sockets.flv"
wget "http://videos.securitytube.net/TCP-Packet-Injection-\(2\).flv"
wget "http://videos.securitytube.net/TCP-Packet-Injection.flv"
wget "http://videos.securitytube.net/TCP-Packet-Sniffer-Programming-.flv"
wget "http://videos.securitytube.net/TKIP-Introduction-\(Part-I\).flv"
wget "http://videos.securitytube.net/TKIP-Introduction-\(Part-II\).flv"
wget "http://videos.securitytube.net/TKIP-Primer-\(Part-I\).flv"
wget "http://videos.securitytube.net/TKIP-Primer-\(Part-II\).flv"
wget "http://videos.securitytube.net/TKIP-Primer-Decapsulation.flv"
wget "http://videos.securitytube.net/TKIP-Primer-Encapsulation.flv"
wget "http://videos.securitytube.net/TKIP-Primer-MIC-\(Message-Integrity-Code\).flv"
wget "http://videos.securitytube.net/TKIP-Primer-Tkip-Sequence-Counter.flv"
wget "http://videos.securitytube.net/TLSAuthentication-Dispensa.flv"
wget "http://videos.securitytube.net/TamperDetection-Johnson.flv"
wget "http://videos.securitytube.net/The-Belgian-Beer-Lovers-Guide-to-Cloud-Security-\(Brucon-2009\).flv"
wget "http://videos.securitytube.net/The-Dangers-of-Social-Networks-\(Brucon-2009\).flv"
wget "http://videos.securitytube.net/The-Day-of-the-Updates-\(Defcon-17\).mp4"
wget "http://videos.securitytube.net/The-Deobfuscator-\(Recon-2008\).flv"
wget "http://videos.securitytube.net/Tracing-Emails-\(Corkys-Security-Series\).flv"
wget "http://videos.securitytube.net/Tracing-Emails-\(Corkys-Security-Series\).wmv"
wget "http://videos.securitytube.net/Tracing.jpg"
wget "http://videos.securitytube.net/Trojans-\(Corkys-Security-Series\).mp4"
wget "http://videos.securitytube.net/Two-Dimensional-Arrays-Part-I-\(C-Programming-101\).flv"
wget "http://videos.securitytube.net/Two-Dimensional-Arrays-Part-II-\(C-Programming-101\).flv"
wget "http://videos.securitytube.net/Two-Dimensional-Arrays-Part-III-\(C-Programming-101\).flv"
wget "http://videos.securitytube.net/Two-very-small-Reverse-Engineering-Tools-\(RECON\).flv"
wget "http://videos.securitytube.net/Under-the-iHood-\(Recon-2008\).flv"
wget "http://videos.securitytube.net/Using-Database-Caches-to-Detect-SQL-injection-\(SecTor-2009\).flv"
wget "http://videos.securitytube.net/Using-Insecure-Networks-with-SSH-Tunneling.swf"
wget "http://videos.securitytube.net/Vehicular-Communication-Basics-\(2\).flv"
wget "http://videos.securitytube.net/Vehicular-Communication-Basics-\(3\).flv"
wget "http://videos.securitytube.net/Vehicular-Communication-Basics.flv"
wget "http://videos.securitytube.net/Virtual-carrier-sensing-\(NAV\)-mechanism.flv"
wget "http://videos.securitytube.net/Vivek-Institute-of-Engineers.flv"
wget "http://videos.securitytube.net/Vulnerability-Scanning-\(Corkys-Security-Series\).flv"
wget "http://videos.securitytube.net/WCF-Holyfield.flv"
wget "http://videos.securitytube.net/WEP-Tutorial-1.flv"
wget "http://videos.securitytube.net/WEP-Tutorial-2.flv"
wget "http://videos.securitytube.net/WEP-Tutorial-3.flv"
wget "http://videos.securitytube.net/WLCCP-Rey.flv"
wget "http://videos.securitytube.net/War-Driving-is-so-2000,-Here-comes-war-shipping.flv"
wget "http://videos.securitytube.net/Webscarab-FOSDEM-2008.flv"
wget "http://videos.securitytube.net/Welcome-to-the-New-IP-Reality-\(Confidence-2008\).flv"
wget "http://videos.securitytube.net/WiFi-MAC-header-\(Part-1\).flv"
wget "http://videos.securitytube.net/WiFi-MAC-header-\(Part-2\).flv"
wget "http://videos.securitytube.net/WiFi-State-Machine-\(Part-1\).flv"
wget "http://videos.securitytube.net/WiFi-State-Machine-\(Part-2\).flv"
wget "http://videos.securitytube.net/WiFi-State-Machine-\(Part-3\).flv"
wget "http://videos.securitytube.net/Wifi-Security,-or-Descending-into-Depression-and-Drink-\(Shmoocon-2010\).flv"
wget "http://videos.securitytube.net/WifiBomb-Kingtuna.flv"
wget "http://videos.securitytube.net/Windows-File-Pseudonyms-\(Shmoocon-2010\).flv"
wget "http://videos.securitytube.net/Windows-Privilege-Escalation-through-LPC-and-ALPC-Interfaces-\(Recon-2008\).flv"
wget "http://videos.securitytube.net/Windows7ISSA.flv"
wget "http://videos.securitytube.net/Windows7ISSA.mp4"
wget "http://videos.securitytube.net/Wireless-Frames--Format-and-Types.flv"
wget "http://videos.securitytube.net/Wireless-LAN-Basics-\(Acknowledgement-Packet-101\).flv"
wget "http://videos.securitytube.net/Wireless-Security-\(Confidence-2008\).flv"
wget "http://videos.securitytube.net/WirelessSecurity-Kershaw.flv"
wget "http://videos.securitytube.net/Wireshark-Basics-\(1\).flv"
wget "http://videos.securitytube.net/Wireshark-Basics-\(2\).flv"
wget "http://videos.securitytube.net/Wireshark-Basics-\(3\).flv"
wget "http://videos.securitytube.net/Wireshark-inject-\(Tutorial\).flv"
wget "http://videos.securitytube.net/XSSF-1.flv"
wget "http://videos.securitytube.net/XSSF-2.flv"
wget "http://videos.securitytube.net/Xdoor-\(Ajax-based-Backdoor\).flv"
wget "http://videos.securitytube.net/Xerxes-Demo.flv"
wget "http://videos.securitytube.net/Zero-Day-Demos-\(2wire-CD35-Authentication-Bypass\).mp4"
wget "http://videos.securitytube.net/Zero-Day-Demos-\(2wire-CD35-Password-Reset\).mp4"
wget "http://videos.securitytube.net/Zero-Day-Demos-\(2wire-Gateway-Routers-Configuration-Disclosure\).swf"
wget "http://videos.securitytube.net/Zero-Day-Demos-\(Firefox-Vulnerability\).flv"
wget "http://videos.securitytube.net/Zero-Day-Demos-\(Firefox-Vulnerability\).mp4"
wget "http://videos.securitytube.net/Zero-Day-Demos-\(Firefox-Vulnerability-Discovered-by-Jeremy-Brown\).flv"
wget "http://videos.securitytube.net/attackingback1.flv"
wget "http://videos.securitytube.net/caffe-latte.swf"
wget "http://videos.securitytube.net/cloudburst-vista.swf"
wget "http://videos.securitytube.net/crossdomain.xml"
wget "http://videos.securitytube.net/csrf-redteam.mp4"
wget "http://videos.securitytube.net/dllhijackauditor_sx_new.flv"
wget "http://videos.securitytube.net/fisc.flv"
wget "http://videos.securitytube.net/flv/Domain-Information-Groper-\(-DIG-\)-Basics.flv"
wget "http://videos.securitytube.net/fping-\(Part-1\).flv"
wget "http://videos.securitytube.net/fping-\(Part-2\).flv"
wget "http://videos.securitytube.net/fping-\(Part-3\).flv"
wget "http://videos.securitytube.net/fping-\(Part-4\).flv"
wget "http://videos.securitytube.net/hamster-\(hello\).wmv"
wget "http://videos.securitytube.net/hamster2_0.wmv"
wget "http://videos.securitytube.net/hzzp.avi"
wget "http://videos.securitytube.net/iPhone-Hard-Drive.mp4"
wget "http://videos.securitytube.net/insectmsword.flv"
wget "http://videos.securitytube.net/keygen_inj.swf"
wget "http://videos.securitytube.net/keygen_inj_config.xml"
wget "http://videos.securitytube.net/keygen_inj_controller.swf"
wget "http://videos.securitytube.net/keygen_inj_preload.swf"

echo All done!

